/* ------------------------------------------------------------------
 * Map Editor mockup — sample data + i18n string table.
 * 100% fake, baked-in. Nothing here touches the real mapping.csv / SVGs.
 * Exposed as window.MOCK for the no-build, file://-friendly setup.
 * ------------------------------------------------------------------ */
(function () {
  'use strict';

  /* Collections — long, sentence-like names (matches the real catalog voice).
     `tone` maps to a swatch hue defined in styles.css (theme-agnostic). */
  const COLLECTIONS = [
    { id: 'gen', he: 'אוסף כללי', en: 'General collection', tone: 'slate' },
    { id: 'ref', he: 'עיון — קומת הכניסה', en: 'Reference — entrance floor', tone: 'blue' },
    { id: 'jud', he: 'מדעי היהדות', en: 'Jewish studies', tone: 'amber' },
    { id: 'art', he: 'אמנות ועיצוב', en: 'Art & design', tone: 'rose' },
    { id: 'sci', he: 'מדעים מדויקים', en: 'Exact sciences', tone: 'green' },
    { id: 'soc', he: 'מדעי החברה', en: 'Social sciences', tone: 'violet' },
    { id: 'per', he: 'כתבי עת', en: 'Periodicals', tone: 'teal' },
  ];

  /* Each floor: decorative elements + shelves laid out on an 880×560 board.
     A shelf with entries=[] is empty; `orphans` are entries that have no shelf
     on this map yet (feed the idle "needs attention" nudge + triage mode). */
  const FLOORS = [
    {
      id: 0, he: 'קומה 0', en: 'Floor 0',
      decor: [
        { type: 'room', x: 300, y: 360, w: 300, h: 150, he: 'אולם קריאה א׳', en: 'Reading room A' },
        { type: 'stairs', x: 40, y: 360, w: 90, h: 150 },
        { type: 'entrance', x: 410, y: 516, he: 'כניסה', en: 'Entrance' },
      ],
      shelves: [
        { code: 'A1', x: 60, y: 60, w: 150, h: 26, entries: [{ id: 'e1', col: 'ref', from: '000', to: '099.9' }] },
        { code: 'A2', x: 60, y: 96, w: 150, h: 26, entries: [{ id: 'e2', col: 'ref', from: '100', to: '199.9' }] },
        { code: 'A3', x: 60, y: 132, w: 150, h: 26, entries: [{ id: 'e3', col: 'gen', from: '200', to: '289.5' }] },
        { code: 'A4', x: 60, y: 168, w: 150, h: 26, entries: [] },
        { code: 'B1', x: 250, y: 60, w: 150, h: 26, entries: [{ id: 'e4', col: 'soc', from: '300', to: '349.9' }] },
        { code: 'B2', x: 250, y: 96, w: 150, h: 26, entries: [
            { id: 'e5', col: 'soc', from: '350', to: '369.5' },
            { id: 'e6', col: 'soc', from: '365', to: '380' } /* deliberate overlap → inline warning */
        ] },
        { code: 'B3', x: 250, y: 132, w: 150, h: 26, entries: [{ id: 'e7', col: 'gen', from: '381', to: '420' }] },
        { code: 'C1', x: 650, y: 60, w: 150, h: 26, entries: [{ id: 'e8', col: 'sci', from: '500', to: '549.9' }] },
        { code: 'C2', x: 650, y: 96, w: 150, h: 26, entries: [{ id: 'e9', col: 'sci', from: '550', to: '599.9' }] },
        { code: 'C3', x: 650, y: 132, w: 150, h: 26, entries: [{ id: 'e10', col: 'sci', from: '600', to: '659' }] },
        { code: 'C4', x: 650, y: 168, w: 150, h: 26, entries: [] },
      ],
      orphans: [
        { id: 'o1', col: 'jud', from: '296', to: '296.4', reason: 'wrongSvgCode' },
      ],
    },
    {
      id: 1, he: 'קומה 1', en: 'Floor 1',
      decor: [
        { type: 'room', x: 330, y: 70, w: 230, h: 120, he: 'מתחם עיון', en: 'Reference area' },
        { type: 'stairs', x: 760, y: 380, w: 90, h: 150 },
        { type: 'entrance', x: 60, y: 300, he: 'מעלית', en: 'Elevator' },
      ],
      shelves: [
        { code: 'D1', x: 60, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'f1', col: 'art', from: '700', to: '724' }] },
        { code: 'D2', x: 100, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'f2', col: 'art', from: '725', to: '749.9' }] },
        { code: 'D3', x: 140, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'f3', col: 'art', from: '750', to: '779' }] },
        { code: 'D4', x: 180, y: 60, w: 26, h: 150, orient: 'v', entries: [] },
        { code: 'E1', x: 60, y: 360, w: 160, h: 26, entries: [{ id: 'f4', col: 'jud', from: '800', to: '839.9' }] },
        { code: 'E2', x: 60, y: 396, w: 160, h: 26, entries: [{ id: 'f5', col: 'jud', from: '840', to: '889.5' }] },
        { code: 'E3', x: 60, y: 432, w: 160, h: 26, entries: [{ id: 'f6', col: 'gen', from: '890', to: '919.9' }] },
        { code: 'F1', x: 620, y: 70, w: 26, h: 120, orient: 'v', entries: [{ id: 'f7', col: 'per', from: 'A', to: 'F' }] },
        { code: 'F2', x: 660, y: 70, w: 26, h: 120, orient: 'v', entries: [{ id: 'f8', col: 'per', from: 'G', to: 'M' }] },
        { code: 'F3', x: 700, y: 70, w: 26, h: 120, orient: 'v', entries: [{ id: 'f9', col: 'per', from: 'N', to: 'Z' }] },
        { code: 'G1', x: 600, y: 360, w: 200, h: 26, entries: [{ id: 'f10', col: 'sci', from: '920', to: '969.9' }] },
        { code: 'G2', x: 600, y: 396, w: 200, h: 26, entries: [] },
      ],
      orphans: [],
    },
    {
      id: 2, he: 'קומה 2', en: 'Floor 2',
      decor: [
        { type: 'room', x: 300, y: 330, w: 320, h: 180, he: 'אולם קריאה ב׳', en: 'Reading room B' },
        { type: 'stairs', x: 40, y: 60, w: 90, h: 150 },
        { type: 'entrance', x: 430, y: 516, he: 'כניסה', en: 'Entrance' },
      ],
      shelves: [
        { code: 'A', x: 200, y: 60, w: 170, h: 26, entries: [
            { id: 'g1', col: 'jud', from: '296.1', to: '296.39' },
            { id: 'g2', col: 'jud', from: '296.4', to: '296.8' },
            { id: 'g3', col: 'gen', from: '297', to: '299.9' }
        ] },
        { code: 'B', x: 200, y: 96, w: 170, h: 26, entries: [{ id: 'g4', col: 'jud', from: '221', to: '249.9' }] },
        { code: 'C', x: 200, y: 132, w: 170, h: 26, entries: [{ id: 'g5', col: 'jud', from: '250', to: '289.9' }] },
        { code: 'D', x: 200, y: 168, w: 170, h: 26, entries: [] },
        { code: 'H1', x: 420, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'g6', col: 'soc', from: '301', to: '319' }] },
        { code: 'H2', x: 460, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'g7', col: 'soc', from: '320', to: '339.9' }] },
        { code: 'H3', x: 500, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'g8', col: 'soc', from: '340', to: '369' }] },
        { code: 'J1', x: 650, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'g9', col: 'art', from: '740', to: '759.9' }] },
        { code: 'J2', x: 690, y: 60, w: 26, h: 150, orient: 'v', entries: [{ id: 'g10', col: 'art', from: '760', to: '779.9' }] },
        { code: 'J3', x: 730, y: 60, w: 26, h: 150, orient: 'v', entries: [] },
        { code: 'K1', x: 60, y: 360, w: 170, h: 26, entries: [{ id: 'g11', col: 'gen', from: '430', to: '469.9' }] },
        { code: 'K2', x: 60, y: 396, w: 170, h: 26, entries: [{ id: 'g12', col: 'gen', from: '470', to: '499.9' }] },
        { code: 'K3', x: 60, y: 432, w: 170, h: 26, entries: [{ id: 'g13', col: 'ref', from: '030', to: '069.9' }] },
        { code: 'L1', x: 690, y: 360, w: 150, h: 26, entries: [{ id: 'g14', col: 'sci', from: '510', to: '549.9' }] },
        { code: 'L2', x: 690, y: 396, w: 150, h: 26, entries: [{ id: 'g15', col: 'sci', from: '550', to: '589.9' }] },
      ],
      orphans: [
        { id: 'o2', col: 'art', from: '780', to: '789.9', reason: 'wrongSvgCode' },
        { id: 'o3', col: 'gen', from: '', to: '', reason: 'missingSvgCode' },
      ],
    },
  ];

  /* String table — plain, first-person, jargon-free (the #73/#78 voice).
     Tokens like {n}, {label} are replaced caller-side. */
  const STR = {
    he: {
      'app.title': 'מפת מדפים — תצוגת עיצוב',
      'app.subtitle': 'תצוגה מקדימה לבחירת מראה. אפשר לשחק בחופשיות — שום נתון אמיתי לא נשמר ולא משתנה.',
      'app.previewBadge': 'תצוגת עיצוב',
      'style.label': 'מראה',
      'style.a': 'קלאסי',
      'style.b': 'חמים',
      'style.c': 'מודרני',
      'lang.toggle': 'English',
      'floor.label': 'קומה',
      'panel.collapse': 'הסתר פאנל',
      'panel.expand': 'הצג פאנל',
      'reset': 'איפוס',
      'help': 'איך נותנים משוב?',
      'batch.note': 'בתצוגה זו: מתקנים את עריכת הטווחים (המיקוד נשאר בזמן הקלדה, וטווח שנשמר נשאר על המסך) ומאחדים את הפאנל הצדדי. שני תיקונים נוספים בחבילה אינם נראים כאן כי הם בצד השרת.',
      'mapEditor.empty': 'בחר מדף במפה ואציג מה נמצא עליו.',
      'mapEditor.empty.hint': 'אפשר גם להחליף קומה למעלה, או לעבור בין שלושת המראֶה.',
      'mapEditor.idle.nudge': '⚠ {n} מדפים בקומה זו דורשים טיפול',
      'mapEditor.idle.nudge.expand': 'הצג לי ←',
      'mapEditor.triage.title': 'שורות שעדיין לא הוצמדו למפה',
      'mapEditor.triage.empty': 'אין מה לתקן בקומה זו.',
      'mapEditor.triage.back': '→ חזרה למפה',
      'mapEditor.triage.card.wrongSvgCode': 'המדף שלה כבר לא נמצא במפה הזו',
      'mapEditor.triage.card.missingSvgCode': 'עדיין לא נבחר מדף',
      'mapEditor.triage.card.setShelf': 'בחר את המדף שלה במפה',
      'mapEditor.shelf.header': 'מדף {label}',
      'mapEditor.shelf.count': '{n} שורות כאן',
      'mapEditor.shelf.back': '→ חזרה למפה',
      'mapEditor.shelf.empty.message': 'עדיין אין כלום על המדף הזה.',
      'mapEditor.shelf.empty.cta': 'הוסף שורה ראשונה',
      'mapEditor.field.collection': 'אוסף',
      'mapEditor.field.from': 'מ-',
      'mapEditor.field.to': 'עד-',
      'mapEditor.addRange': '+ הוסף שורה נוספת',
      'mapEditor.move': 'העבר למדף אחר',
      'mapEditor.delete': 'הסר',
      'mapEditor.delete.confirm': 'להסיר את השורה הזו?',
      'mapEditor.warning.startGtEnd': 'ה־"מ-" גבוה מה־"עד-" — בדקו בבקשה.',
      'mapEditor.warning.overlap': 'מספרי המיון האלה חופפים לשורה אחרת על מדף זה.',
      'mapEditor.warning.banner': '{n} דברים לבדוק במדף זה',
      'mapEditor.reassign.title': 'העברת שורה',
      'mapEditor.reassign.banner.move': 'עכשיו לחץ על המדף שאליו זה שייך',
      'mapEditor.reassign.moving': 'מעביר: {what}',
      'mapEditor.reassign.cancel': 'ביטול',
      'mapEditor.save': 'שמור',
      'mapEditor.discard': 'בטל שינויים',
      'mapEditor.saved': 'נשמר ✓',
      'mapEditor.toast.saved': 'השינויים במדף {label} נשמרו.',
      'mapEditor.toast.moved': 'הטווח הועבר למדף {label} בקומה {floor}.',
      'mapEditor.toast.movedSame': 'הטווח הועבר למדף {label}.',
      'mapEditor.toast.added': 'נוספה שורה חדשה למדף {label}.',
      'mapEditor.toast.removed': 'השורה הוסרה ממדף {label}.',
      'mapEditor.toast.reset': 'הכול אופס לנתוני הדוגמה.',
      'mapEditor.pending': '{n} שינויים לא שמורים',
      'legend.title': 'אוספים',
      /* feedback */
      'fb.fab': '💬 משוב',
      'fb.title': 'המשוב שלך',
      'fb.intro': 'מה דעתך על המראה הזה? כתוב הערה, אפשר לצרף צילום מסך, ובסוף שלח לנו את הקובץ.',
      'fb.style': 'מראה נוכחי',
      'fb.topic': 'נושא',
      'fb.topic.map': 'המפה',
      'fb.topic.panel': 'הפאנל הצדדי',
      'fb.topic.fields': 'שדות מ-/עד-',
      'fb.topic.look': 'צבעים וגופנים',
      'fb.topic.wording': 'ניסוח וטקסט',
      'fb.topic.general': 'כללי',
      'fb.comment': 'ההערה שלך',
      'fb.comment.ph': 'מה אהבת, מה הפריע, מה היית משנה…',
      'fb.screenshot': 'צילומי מסך (לא חובה)',
      'fb.screenshot.hint': 'גרור לכאן תמונה, או לחץ לבחירה. אפשר כמה.',
      'fb.add': 'הוסף הערה',
      'fb.list.title': 'הערות שנאספו',
      'fb.list.empty': 'עדיין לא נאספו הערות.',
      'fb.export': 'ייצא ושלח',
      'fb.copy': 'העתק כטקסט',
      'fb.clear': 'נקה הכול',
      'fb.copied': 'ההערות הועתקו ללוח.',
      'fb.exported': 'הקובץ ירד — צרף אותו למייל שנפתח ושלח לנו.',
      'fb.remove': 'מחק',
      /* help */
      'help.title': 'איך נותנים משוב?',
      'help.p1': 'זו תצוגה מקדימה של מסך עריכת המפה. אפשר לשחק בחופשיות — כלום פה לא אמיתי ושום נתון לא נשמר אצלנו.',
      'help.s1.t': '1. בחר מראה',
      'help.s1.d': 'למעלה יש שלושה כפתורים — קלאסי / חמים / מודרני. כל אחד מציג את אותו מסך בעיצוב אחר. עבור ביניהם וראה מה מתאים.',
      'help.s2.t': '2. שחק עם המסך',
      'help.s2.d': 'לחץ על מדף במפה כדי לראות ולערוך מה עליו, החלף קומות, ונסה להוסיף או להעביר טווח. הכול לדוגמה בלבד.',
      'help.s3.t': '3. כתוב לנו',
      'help.s3.d': 'לחץ על כפתור "משוב" בפינה. כתוב הערה, אפשר לצרף צילום מסך, והוסף אותה. בסוף לחץ "ייצא ושלח" — יירד קובץ אחד ויפתח מייל. צרף את הקובץ ושלח אלינו.',
      'help.close': 'הבנתי, בוא נתחיל',
    },
    en: {
      'app.title': 'Shelf map — design preview',
      'app.subtitle': 'A look-and-feel preview. Play freely — no real data is saved or changed.',
      'app.previewBadge': 'Design preview',
      'style.label': 'Style',
      'style.a': 'Classic',
      'style.b': 'Warm',
      'style.c': 'Modern',
      'lang.toggle': 'עברית',
      'floor.label': 'Floor',
      'panel.collapse': 'Hide panel',
      'panel.expand': 'Show panel',
      'reset': 'Reset',
      'help': 'How to give feedback',
      'batch.note': 'This preview fixes range editing (your cursor stays put while typing, and a saved range stays on screen) and unifies the side panel. Two more fixes in this batch are server-side and aren’t visible here.',
      'mapEditor.empty': 'Pick a shelf on the map and I’ll show what’s on it.',
      'mapEditor.empty.hint': 'You can also switch floors above, or try the three styles.',
      'mapEditor.idle.nudge': '⚠ {n} shelves on this floor need attention',
      'mapEditor.idle.nudge.expand': 'Show me →',
      'mapEditor.triage.title': 'Entries that aren’t on the map yet',
      'mapEditor.triage.empty': 'Nothing needs fixing on this floor.',
      'mapEditor.triage.back': '→ Back to map',
      'mapEditor.triage.card.wrongSvgCode': 'Its shelf isn’t on this map anymore',
      'mapEditor.triage.card.missingSvgCode': 'No shelf chosen yet',
      'mapEditor.triage.card.setShelf': 'Choose its shelf on the map',
      'mapEditor.shelf.header': 'Shelf {label}',
      'mapEditor.shelf.count': '{n} entries here',
      'mapEditor.shelf.back': '→ Back to map',
      'mapEditor.shelf.empty.message': 'Nothing is on this shelf yet.',
      'mapEditor.shelf.empty.cta': 'Add the first entry',
      'mapEditor.field.collection': 'Collection',
      'mapEditor.field.from': 'From',
      'mapEditor.field.to': 'To',
      'mapEditor.addRange': '+ Add another entry',
      'mapEditor.move': 'Move to another shelf',
      'mapEditor.delete': 'Remove',
      'mapEditor.delete.confirm': 'Remove this entry?',
      'mapEditor.warning.startGtEnd': '“From” is higher than “To” — please check.',
      'mapEditor.warning.overlap': 'These call numbers overlap with another entry on this shelf.',
      'mapEditor.warning.banner': '{n} things to check on this shelf',
      'mapEditor.reassign.title': 'Moving an entry',
      'mapEditor.reassign.banner.move': 'Now click the shelf where this belongs',
      'mapEditor.reassign.moving': 'Moving: {what}',
      'mapEditor.reassign.cancel': 'Never mind',
      'mapEditor.save': 'Save',
      'mapEditor.discard': 'Undo my changes',
      'mapEditor.saved': 'Saved ✓',
      'mapEditor.toast.saved': 'Your changes to shelf {label} were saved.',
      'mapEditor.toast.moved': 'Moved the range to shelf {label} on Floor {floor}.',
      'mapEditor.toast.movedSame': 'Moved the range to shelf {label}.',
      'mapEditor.toast.added': 'Added a new entry to shelf {label}.',
      'mapEditor.toast.removed': 'Removed the entry from shelf {label}.',
      'mapEditor.toast.reset': 'Everything reset to the sample data.',
      'mapEditor.pending': '{n} unsaved changes',
      'legend.title': 'Collections',
      'fb.fab': '💬 Feedback',
      'fb.title': 'Your feedback',
      'fb.intro': 'What do you think of this look? Write a note, optionally attach a screenshot, then send us the file.',
      'fb.style': 'Current style',
      'fb.topic': 'Topic',
      'fb.topic.map': 'The map',
      'fb.topic.panel': 'The side panel',
      'fb.topic.fields': 'From / To fields',
      'fb.topic.look': 'Colors & fonts',
      'fb.topic.wording': 'Wording & text',
      'fb.topic.general': 'General',
      'fb.comment': 'Your note',
      'fb.comment.ph': 'What you liked, what bugged you, what you’d change…',
      'fb.screenshot': 'Screenshots (optional)',
      'fb.screenshot.hint': 'Drag an image here, or click to choose. Several are fine.',
      'fb.add': 'Add note',
      'fb.list.title': 'Collected notes',
      'fb.list.empty': 'No notes collected yet.',
      'fb.export': 'Export & send',
      'fb.copy': 'Copy as text',
      'fb.clear': 'Clear all',
      'fb.copied': 'Notes copied to the clipboard.',
      'fb.exported': 'The file downloaded — attach it to the email that just opened and send it to us.',
      'fb.remove': 'Delete',
      'help.title': 'How to give feedback',
      'help.p1': 'This is a preview of the shelf-map editing screen. Play freely — nothing here is real and no data is saved on our side.',
      'help.s1.t': '1. Pick a style',
      'help.s1.d': 'Up top there are three buttons — Classic / Warm / Modern. Each shows the same screen in a different look. Switch between them and see what fits.',
      'help.s2.t': '2. Play with the screen',
      'help.s2.d': 'Click a shelf on the map to see and edit what’s on it, switch floors, and try adding or moving a range. It’s all sample data.',
      'help.s3.t': '3. Tell us',
      'help.s3.d': 'Click the “Feedback” button in the corner. Write a note, optionally attach a screenshot, and add it. When done, click “Export & send” — one file downloads and an email opens. Attach the file and send it to us.',
      'help.close': 'Got it, let’s start',
    },
  };

  window.MOCK = { COLLECTIONS, FLOORS, STR, FEEDBACK_EMAIL: 'hagaybar@tauex.tau.ac.il' };
})();
