/* ------------------------------------------------------------------
 * Map Editor mockup — sample data + i18n string table.
 * 100% fake, baked-in. Nothing here touches the real mapping.csv / SVGs.
 * Exposed as window.MOCK for the no-build, file://-friendly setup.
 * ------------------------------------------------------------------ */
(function () {
  'use strict';

  /* Collections — long, sentence-like names (matches the real catalog voice).
     `tone` maps to a swatch hue defined in styles.css (theme-agnostic). */
  const COLLECTIONS = [
    { id: 'gen', he: 'אוסף כללי', en: 'General collection', tone: 'slate' },
    { id: 'ref', he: 'עיון — קומת הכניסה', en: 'Reference — entrance floor', tone: 'blue' },
    { id: 'jud', he: 'מדעי היהדות', en: 'Jewish studies', tone: 'amber' },
    { id: 'art', he: 'אמנות ועיצוב', en: 'Art & design', tone: 'rose' },
    { id: 'sci', he: 'מדעים מדויקים', en: 'Exact sciences', tone: 'green' },
    { id: 'soc', he: 'מדעי החברה', en: 'Social sciences', tone: 'violet' },
    { id: 'per', he: 'כתבי עת', en: 'Periodicals', tone: 'teal' },
  ];

  /* Floors render the REAL production SVGs (duplicated into this folder).
     Shelf codes come from the SVG at runtime (data-map-object="shelf" + id);
     app.js seeds sample ranges onto a subset of those real codes. */
  const FLOOR_META = [
    { id: 0, he: 'קומה 0', en: 'Floor 0' },
    { id: 1, he: 'קומה 1', en: 'Floor 1' },
    { id: 2, he: 'קומה 2', en: 'Floor 2' },
  ];

  /* Sample ranges seeded onto real shelves (cycled, varied by index in app.js).
     Plain Dewey-ish numbers + the collection they belong to. */
  const SAMPLE_RANGES = [
    { col: 'jud', from: '221', to: '249.9' },
    { col: 'jud', from: '296.1', to: '296.39' },
    { col: 'soc', from: '301', to: '319' },
    { col: 'soc', from: '320', to: '339.9' },
    { col: 'ref', from: '030', to: '069.9' },
    { col: 'gen', from: '430', to: '469.9' },
    { col: 'sci', from: '510', to: '549.9' },
    { col: 'sci', from: '550', to: '589.9' },
    { col: 'art', from: '740', to: '759.9' },
    { col: 'art', from: '760', to: '779.9' },
    { col: 'per', from: 'A', to: 'F' },
    { col: 'gen', from: '890', to: '919.9' },
  ];

  /* Synthetic "needs a shelf" items per floor — codes intentionally NOT on the
     map (feed the idle nudge + triage mode). reason ∈ wrongSvgCode|missingSvgCode. */
  const ORPHANS = {
    0: [],
    1: [{ id: 'o1', col: 'jud', from: '296', to: '296.4', reason: 'wrongSvgCode' }],
    2: [
      { id: 'o2', col: 'art', from: '780', to: '789.9', reason: 'wrongSvgCode' },
      { id: 'o3', col: 'gen', from: '', to: '', reason: 'missingSvgCode' },
    ],
  };

  /* String table — plain, first-person, jargon-free (the #73/#78 voice).
     Tokens like {n}, {label} are replaced caller-side. */
  const STR = {
    he: {
      'app.title': 'מפת מדפים — תצוגת עיצוב',
      'app.subtitle': 'תצוגה מקדימה לבחירת מראה. אפשר לשחק בחופשיות — שום נתון אמיתי לא נשמר ולא משתנה.',
      'app.previewBadge': 'תצוגת עיצוב',
      'style.label': 'מראה',
      'style.a': 'קלאסי',
      'style.b': 'חמים',
      'style.c': 'מודרני',
      'lang.toggle': 'English',
      'floor.label': 'קומה',
      'panel.collapse': 'הסתר פאנל',
      'panel.expand': 'הצג פאנל',
      'reset': 'איפוס',
      'help': 'איך נותנים משוב?',
      'batch.note': 'בתצוגה זו: מתקנים את עריכת הטווחים (המיקוד נשאר בזמן הקלדה, וטווח שנשמר נשאר על המסך) ומאחדים את הפאנל הצדדי. שני תיקונים נוספים בחבילה אינם נראים כאן כי הם בצד השרת.',
      'mapEditor.empty': 'בחר מדף במפה ואציג מה נמצא עליו.',
      'mapEditor.empty.hint': 'אפשר גם להחליף קומה למעלה, או לעבור בין שלושת המראֶה.',
      'mapEditor.idle.nudge': '⚠ {n} מדפים בקומה זו דורשים טיפול',
      'mapEditor.idle.nudge.expand': 'הצג לי ←',
      'mapEditor.triage.title': 'שורות שעדיין לא הוצמדו למפה',
      'mapEditor.triage.empty': 'אין מה לתקן בקומה זו.',
      'mapEditor.triage.back': '→ חזרה למפה',
      'mapEditor.triage.card.wrongSvgCode': 'המדף שלה כבר לא נמצא במפה הזו',
      'mapEditor.triage.card.missingSvgCode': 'עדיין לא נבחר מדף',
      'mapEditor.triage.card.setShelf': 'בחר את המדף שלה במפה',
      'mapEditor.shelf.header': 'מדף {label}',
      'mapEditor.shelf.count': '{n} שורות כאן',
      'mapEditor.shelf.back': '→ חזרה למפה',
      'mapEditor.shelf.empty.message': 'עדיין אין כלום על המדף הזה.',
      'mapEditor.shelf.empty.cta': 'הוסף שורה ראשונה',
      'mapEditor.field.collection': 'אוסף',
      'mapEditor.field.from': 'מ-',
      'mapEditor.field.to': 'עד-',
      'mapEditor.addRange': '+ הוסף שורה נוספת',
      'mapEditor.move': 'העבר למדף אחר',
      'mapEditor.delete': 'הסר',
      'mapEditor.delete.confirm': 'להסיר את השורה הזו?',
      'mapEditor.warning.startGtEnd': 'ה־"מ-" גבוה מה־"עד-" — בדקו בבקשה.',
      'mapEditor.warning.overlap': 'מספרי המיון האלה חופפים לשורה אחרת על מדף זה.',
      'mapEditor.warning.banner': '{n} דברים לבדוק במדף זה',
      'mapEditor.reassign.title': 'העברת שורה',
      'mapEditor.reassign.banner.move': 'עכשיו לחץ על המדף שאליו זה שייך',
      'mapEditor.reassign.moving': 'מעביר: {what}',
      'mapEditor.reassign.cancel': 'ביטול',
      'mapEditor.save': 'שמור',
      'mapEditor.discard': 'בטל שינויים',
      'mapEditor.saved': 'נשמר ✓',
      'mapEditor.toast.saved': 'השינויים במדף {label} נשמרו.',
      'mapEditor.toast.moved': 'הטווח הועבר למדף {label} בקומה {floor}.',
      'mapEditor.toast.movedSame': 'הטווח הועבר למדף {label}.',
      'mapEditor.toast.added': 'נוספה שורה חדשה למדף {label}.',
      'mapEditor.toast.removed': 'השורה הוסרה ממדף {label}.',
      'mapEditor.toast.reset': 'הכול אופס לנתוני הדוגמה.',
      'mapEditor.pending': '{n} שינויים לא שמורים',
      'legend.title': 'אוספים',
      /* feedback */
      'fb.fab': '💬 משוב',
      'fb.title': 'המשוב שלך',
      'fb.intro': 'מה דעתך על המראה הזה? כתוב הערה, אפשר לצרף צילום מסך, ובסוף שלח לנו את הקובץ.',
      'fb.style': 'מראה נוכחי',
      'fb.topic': 'נושא',
      'fb.topic.map': 'המפה',
      'fb.topic.panel': 'הפאנל הצדדי',
      'fb.topic.fields': 'שדות מ-/עד-',
      'fb.topic.look': 'צבעים וגופנים',
      'fb.topic.wording': 'ניסוח וטקסט',
      'fb.topic.general': 'כללי',
      'fb.comment': 'ההערה שלך',
      'fb.comment.ph': 'מה אהבת, מה הפריע, מה היית משנה…',
      'fb.screenshot': 'צילומי מסך (לא חובה)',
      'fb.screenshot.hint': 'גרור לכאן תמונה, או לחץ לבחירה. אפשר כמה.',
      'fb.add': 'הוסף הערה',
      'fb.list.title': 'הערות שנאספו',
      'fb.list.empty': 'עדיין לא נאספו הערות.',
      'fb.export': 'ייצא ושלח',
      'fb.copy': 'העתק כטקסט',
      'fb.clear': 'נקה הכול',
      'fb.copied': 'ההערות הועתקו ללוח.',
      'fb.exported': 'הקובץ ירד — צרף אותו למייל שנפתח ושלח לנו.',
      'fb.remove': 'מחק',
      /* help */
      'help.title': 'איך נותנים משוב?',
      'help.p1': 'זו תצוגה מקדימה של מסך עריכת המפה. אפשר לשחק בחופשיות — כלום פה לא אמיתי ושום נתון לא נשמר אצלנו.',
      'help.s1.t': '1. בחר מראה',
      'help.s1.d': 'למעלה יש שלושה כפתורים — קלאסי / חמים / מודרני. כל אחד מציג את אותו מסך בעיצוב אחר. עבור ביניהם וראה מה מתאים.',
      'help.s2.t': '2. שחק עם המסך',
      'help.s2.d': 'לחץ על מדף במפה כדי לראות ולערוך מה עליו, החלף קומות, ונסה להוסיף או להעביר טווח. הכול לדוגמה בלבד.',
      'help.s3.t': '3. כתוב לנו',
      'help.s3.d': 'לחץ על כפתור "משוב" בפינה. כתוב הערה, אפשר לצרף צילום מסך, והוסף אותה. בסוף לחץ "ייצא ושלח" — יירד קובץ אחד ויפתח מייל. צרף את הקובץ ושלח אלינו.',
      'help.close': 'הבנתי, בוא נתחיל',
    },
    en: {
      'app.title': 'Shelf map — design preview',
      'app.subtitle': 'A look-and-feel preview. Play freely — no real data is saved or changed.',
      'app.previewBadge': 'Design preview',
      'style.label': 'Style',
      'style.a': 'Classic',
      'style.b': 'Warm',
      'style.c': 'Modern',
      'lang.toggle': 'עברית',
      'floor.label': 'Floor',
      'panel.collapse': 'Hide panel',
      'panel.expand': 'Show panel',
      'reset': 'Reset',
      'help': 'How to give feedback',
      'batch.note': 'This preview fixes range editing (your cursor stays put while typing, and a saved range stays on screen) and unifies the side panel. Two more fixes in this batch are server-side and aren’t visible here.',
      'mapEditor.empty': 'Pick a shelf on the map and I’ll show what’s on it.',
      'mapEditor.empty.hint': 'You can also switch floors above, or try the three styles.',
      'mapEditor.idle.nudge': '⚠ {n} shelves on this floor need attention',
      'mapEditor.idle.nudge.expand': 'Show me →',
      'mapEditor.triage.title': 'Entries that aren’t on the map yet',
      'mapEditor.triage.empty': 'Nothing needs fixing on this floor.',
      'mapEditor.triage.back': '→ Back to map',
      'mapEditor.triage.card.wrongSvgCode': 'Its shelf isn’t on this map anymore',
      'mapEditor.triage.card.missingSvgCode': 'No shelf chosen yet',
      'mapEditor.triage.card.setShelf': 'Choose its shelf on the map',
      'mapEditor.shelf.header': 'Shelf {label}',
      'mapEditor.shelf.count': '{n} entries here',
      'mapEditor.shelf.back': '→ Back to map',
      'mapEditor.shelf.empty.message': 'Nothing is on this shelf yet.',
      'mapEditor.shelf.empty.cta': 'Add the first entry',
      'mapEditor.field.collection': 'Collection',
      'mapEditor.field.from': 'From',
      'mapEditor.field.to': 'To',
      'mapEditor.addRange': '+ Add another entry',
      'mapEditor.move': 'Move to another shelf',
      'mapEditor.delete': 'Remove',
      'mapEditor.delete.confirm': 'Remove this entry?',
      'mapEditor.warning.startGtEnd': '“From” is higher than “To” — please check.',
      'mapEditor.warning.overlap': 'These call numbers overlap with another entry on this shelf.',
      'mapEditor.warning.banner': '{n} things to check on this shelf',
      'mapEditor.reassign.title': 'Moving an entry',
      'mapEditor.reassign.banner.move': 'Now click the shelf where this belongs',
      'mapEditor.reassign.moving': 'Moving: {what}',
      'mapEditor.reassign.cancel': 'Never mind',
      'mapEditor.save': 'Save',
      'mapEditor.discard': 'Undo my changes',
      'mapEditor.saved': 'Saved ✓',
      'mapEditor.toast.saved': 'Your changes to shelf {label} were saved.',
      'mapEditor.toast.moved': 'Moved the range to shelf {label} on Floor {floor}.',
      'mapEditor.toast.movedSame': 'Moved the range to shelf {label}.',
      'mapEditor.toast.added': 'Added a new entry to shelf {label}.',
      'mapEditor.toast.removed': 'Removed the entry from shelf {label}.',
      'mapEditor.toast.reset': 'Everything reset to the sample data.',
      'mapEditor.pending': '{n} unsaved changes',
      'legend.title': 'Collections',
      'fb.fab': '💬 Feedback',
      'fb.title': 'Your feedback',
      'fb.intro': 'What do you think of this look? Write a note, optionally attach a screenshot, then send us the file.',
      'fb.style': 'Current style',
      'fb.topic': 'Topic',
      'fb.topic.map': 'The map',
      'fb.topic.panel': 'The side panel',
      'fb.topic.fields': 'From / To fields',
      'fb.topic.look': 'Colors & fonts',
      'fb.topic.wording': 'Wording & text',
      'fb.topic.general': 'General',
      'fb.comment': 'Your note',
      'fb.comment.ph': 'What you liked, what bugged you, what you’d change…',
      'fb.screenshot': 'Screenshots (optional)',
      'fb.screenshot.hint': 'Drag an image here, or click to choose. Several are fine.',
      'fb.add': 'Add note',
      'fb.list.title': 'Collected notes',
      'fb.list.empty': 'No notes collected yet.',
      'fb.export': 'Export & send',
      'fb.copy': 'Copy as text',
      'fb.clear': 'Clear all',
      'fb.copied': 'Notes copied to the clipboard.',
      'fb.exported': 'The file downloaded — attach it to the email that just opened and send it to us.',
      'fb.remove': 'Delete',
      'help.title': 'How to give feedback',
      'help.p1': 'This is a preview of the shelf-map editing screen. Play freely — nothing here is real and no data is saved on our side.',
      'help.s1.t': '1. Pick a style',
      'help.s1.d': 'Up top there are three buttons — Classic / Warm / Modern. Each shows the same screen in a different look. Switch between them and see what fits.',
      'help.s2.t': '2. Play with the screen',
      'help.s2.d': 'Click a shelf on the map to see and edit what’s on it, switch floors, and try adding or moving a range. It’s all sample data.',
      'help.s3.t': '3. Tell us',
      'help.s3.d': 'Click the “Feedback” button in the corner. Write a note, optionally attach a screenshot, and add it. When done, click “Export & send” — one file downloads and an email opens. Attach the file and send it to us.',
      'help.close': 'Got it, let’s start',
    },
  };

  window.MOCK = { COLLECTIONS, FLOOR_META, SAMPLE_RANGES, ORPHANS, STR, FEEDBACK_EMAIL: 'hagaybar@tauex.tau.ac.il' };
})();
